#ifndef QDEVICEWATCHER_GLOBAL_HPP
#define QDEVICEWATCHER_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QDEVICEWATCHER_LIBRARY)
#define QDEVICEWATCHERSHARED_EXPORT Q_DECL_EXPORT
#else
#define QDEVICEWATCHERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QDEVICEWATCHER_GLOBAL_HPP
